export const START_RECORD_FETCH='START_RECORD_FETCH';
export const FETCH_RECORD_SUCCESS='FETCH_RECORD_SUCCESS';
export const FETCH_RECORD_FAIL='FETCH_RECORD_FAIL';

export const START_RECORD_SAVE='START_RECORD_SAVE';
export const SAVE_RECORD_SUCCESS='SAVE_RECORD_SUCCESS';
export const SAVE_RECORD_FAIL='SAVE_RECORD_FAIL';

export const START_RECORD_EDIT='START_RECORD_EDIT';
export const EDIT_RECORD_SUCCESS='EDIT_RECORD_SUCCESS';
export const EDIT_RECORD_FAIL='EDIT_RECORD_FAIL';

