export const START_PATIENT_FETCH='START_PATIENT_FETCH';
export const FETCH_PATIENT_SUCCESS='FETCH_PATIENT_SUCCESS';
export const FETCH_PATIENT_FAIL='FETCH_PATIENT_FAIL';

export const START_PATIENT_SAVE='START_PATIENT_SAVE';
export const SAVE_PATIENT_SUCCESS='SAVE_PATIENT_SUCCESS';
export const SAVE_PATIENT_FAIL='SAVE_PATIENT_FAIL';

export const START_PATIENT_EDIT='START_PATIENT_EDIT';
export const EDIT_PATIENT_SUCCESS='EDIT_PATIENT_SUCCESS';
export const EDIT_PATIENT_FAIL='EDIT_PATIENT_FAIL';

